version: '3'
services:
   jupyterlab-{{cookiecutter.repo_name}}:
      container_name: jupyterlab-{{cookiecutter.repo_name}}
      build: ..
      ports:
         - "127.0.0.1::8888:8888"
      volumes:
         - ../:/mnt
      entrypoint: sh -c "cd /mnt && pip install -e . && jupyter lab --NotebookApp.token='' --ip=0.0.0.0 --no-browser --allow-root"
      stdin_open: true
      tty: true
