version: '3'
services:
   jupyterlab-server:
      build: .
      ports:
         - "127.0.0.1::8888"
      volumes:
         - ./:/mnt
      entrypoint: bash -c "cd /mnt && jupyter lab --NotebookApp.token='' --ip=0.0.0.0 --allow-root"
      stdin_open: true
      tty: true

